# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  command = "npm run prerender"
  publish = "dist/concurs-events/browser"
  

# Specific branch context:
# Deploys from this branch will take these settings
# and override their current ones.
[context.branch-deploy]
  command = "npm run prerender"
  publish = "dist/concurs-events/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  # Directory with the serverless Lambda functions
  functions = "lambda_functions"